### ISSUE TITLE
Access your own playlist

### ISSUE THREAD

**Issue by christ59** [ndg63276/alexa-youtube#19] opened 2018-12-20 13:59 UTC
Hello!
Do you know if it will be possible to access the playlists of his youtube account?
Thanks

**Comment by ndg63276** [comment] 2018-12-20 14:15
If it is a public playlist, then you should be able to say "Alexa, ask YouTube to play playlist (name of playlist)". But it will play the first search result, so you might want to make the name distinctive.

**Comment by christ59** [comment] 2018-12-20 14:17
Ok. But if I want to access my playlist that is private?

**Comment by christ59** [comment] 2018-12-20 14:19
I will make it public, it will be easier;)

**Comment by ndg63276** [comment] 2018-12-20 14:23
If you have deployed the skill yourself, with your own YouTube API key, you might be able to access private playlists. You'd have to try it and see.

**Comment by christ59** [comment] 2019-01-02 12:58
Hello and a happy new year 2019!
I have a problem with my playlist.
I put my playlist in public, I gave it a unique name, it appears in 1st position on Youtube (on PC) but my Skill does not read it and starts with the 2nd video. Do you have an idea of the problem ?
Thanks

**Comment by ndg63276** [comment] 2019-01-02 13:02
Can you send me a link to the playlist? If you'd rather not share it here, let me know and you can email it to me.

**Comment by christ59** [comment] 2019-01-07 07:51
> 
> 
> Can you send me a link to the playlist? If you'd rather not share it here, let me know and you can email it to me.

comes in 1st position:
"musiques christophe du nord "
https://www.youtube.com/results?search_query=christophe+du+nord&sp=EgIQAw%253D%253D

Direct access:
https://www.youtube.com/watch?v=ft8Tyxqcw4Q&list=PLLFnyGeZhCiftnui2P1pBkenb352i0bqb

**Comment by ndg63276** [comment] 2019-01-07 10:00
For me, your playlist comes in 2nd position:

![image](https://user-images.githubusercontent.com/24956497/50761615-c1db9900-1262-11e9-8e17-4139d41184b7.png)

You might need to ask for "musiques christophe du nord". I shall put in some sort of "next playlist" function as well.

**Comment by ndg63276** [comment] 2019-01-07 10:32
If you have your own Google developer key, you can go to https://repl.it/@ndg63276/YoutubePlaylistTester, click run at the top, and it will ask for your key, and tell you the top 10 results for that search. It may differ by country I guess, and therefore by dev key, so we don't get the same results.

**Comment by christ59** [comment] 2019-01-07 10:58
My playlist comes in 2nd position.

I found this to be able to access his personal playlists. What do you think ?
https://stackoverflow.com/questions/29626207/how-to-get-private-playlist-ids-through-youtube-api-v3?rq=1

**Comment by ndg63276** [comment] 2019-01-07 11:10
That API doesn't do searching, it will just list your playlists. And as most people use this skill with my dev key, it would only list my playlists.

**Comment by christ59** [comment] 2019-01-07 11:32
It's not super important to access my playlist, it's just that I can not access some playlist because of the language (French Echo + English search = it's the horror :)

I would like to re-write the code but it's not in my skills. But I will continue to search for something like "Alexa, ask Youtube to play MY playlist". (Even if I have to write the link to my playlist in the code of my Skill;))

**Comment by christ59** [comment] 2019-01-07 14:11
When I put it in my browser (by putting my key youtube), my playlist comes in 1st position.
By cons, googleapis starts at 0 and not 1. Would not there be a shift in the numbering? What makes the video that is in 2nd position is placed first? (and my playlist is not taken into account)

https://www.googleapis.com/youtube/v3/search?part=snippet&q=christophe+du+nord&type=playlist&key=MY_YOUTUBE_KEY

**Comment by ndg63276** [comment] 2019-01-07 14:42
Still comes up 2nd for me. I guess the Dev Key affects you search results.

I do always start with the 0 result, that's why playlist['sr'] is set to 0 on line 511 of lambda_function.py.

![image](https://user-images.githubusercontent.com/24956497/50773970-2b22d280-128a-11e9-9221-14fbb351223b.png)

**Comment by christ59** [comment] 2019-01-07 14:52
In "Lambda_function" I try to create a function to read directly my playlist.

I left the function "playlist_search". It would have to go directly to my playlist without doing any research.
It would be necessary to remove all that is useless in this function. Only direct access through its url (https://www.youtube.com/watch?v=ft8Tyxqcw4Q&list=PLLFnyGeZhCiftnui2P1pBkenb352i0bqb)

Can you help me?
Thank you.

**Comment by christ59** [comment] 2019-01-07 15:11
Or perhaps simpler, list the playlists of a channel (which I put in the code: "UCidqxBUO_zV7JMpuumTCAmw")

**Comment by ndg63276** [comment] 2019-01-07 15:16
If you get the code from https://github.com/ndg63276/alexa-youtube/tree/christ59, it will just play your playlist. You just put the playlist id (' PLLFnyGeZhCiftnui2P1pBkenb352i0bqb') as the variable playlist_id.

**Comment by christ59** [comment] 2019-01-07 15:58
It seems to work (in the development console), I have to test my Echo. Thank you

**Comment by ndg63276** [comment] 2019-01-07 20:17
@Carlo-Ita - if you use the files from that branch, whatever playlist you search for, it will play @christ59's playlist. Best to use the main repository - https://github.com/ndg63276/alexa-youtube

**Comment by Carlo-Ita** [comment] 2019-01-08 01:41
thank you for your fast reply,
I already use https://github.com/ndg63276/alexa-youtube and it work good, but I've seen you've done a personalized file for @christ59 that is working on his playlists.
I hoped to use the same file, just changing the playlist ID with mine... but I don't know which is the file where i have to make the change... I thought I only need to change the "index.js" file in the lambda console, but I don't find it... or more simply the "InteractionModel_it.json" file...
p.s. Sorry @christ59 ...!! I absolutely don't wont to invade your privacy and I'm not looking inside your playlist... !!

**Comment by christ59** [comment] 2019-01-08 08:01
@ ndg63276 - It works. I created an Intent to launch my playlist. I still have some changes to make everything work the way I want it. As soon as it's over, I'll share it so I can share it with people who want to access their own playlist. You can delete this branch if you want.

@ Carlo-Ita - No worries :) The goal is to help each other and to have a perfect Skill!

**Comment by ndg63276** [comment] 2019-01-08 09:34
@Carlo-Ita - I've pushed some more changes to this branch, which should help you. What you need to do:

1. Download https://github.com/ndg63276/alexa-youtube/blob/christ59/InteractionModel_it.json, check the translations on lines 115-7 and 124 (I used Google Translate), and then Upload that file to https://developer.amazon.com/alexa/console/ask.

1. Download https://github.com/ndg63276/alexa-youtube/blob/christ59/lambda_function.zip, and then upload it to Lambda, in the Upload a Zip File section.

1. In the Lambda file editor, edit lambda_function.py line 451 with your playlist id, and line 453 with your playlist title.

**Comment by ndg63276** [comment] 2019-01-08 09:35
@christ59 - Great. I've uploaded some changes to help Carlo, I imagine very similar to what you've done with your own intent.

**Comment by Carlo-Ita** [comment] 2019-01-10 03:02
@ndg63276 - thank you very much for your disponibility !!! Anyway I followed your directions, but something does not work as it should...
This it's what I've done:

- open https://github.com/ndg63276/alexa-youtube/blob/christ59/InteractionModel_it.json
click raw, select all, copy
- open alexa developer console
click Youtube Skills, json editor, select all, delete, paste, save model, build model

- open https://github.com/ndg63276/alexa-youtube/blob/christ59/lambda_function.zip
download zip
- open AWS, click lambda, YoutubeSkills, modify function code, choose a zip, upload lambda_function.zip,
(error opening file - could not open file: /index.js - the file could not be found on the file system - ok)
- click save

At this point if I ask "Alexa, chiedi a youtube": "Inizia la mia playlist", or "Ascolta la mia playlist", or "Riprodurre la mia playlist" (these are the sentences in the InteractionModel_it.json)
The answer is: "There is a problem with this skill"
If I ask "Alexa, chiedi a youtube": "Riproduci la mia playlist"
It play this italian video: https://www.youtube.com/watch?v=HlOD2k9q4JM (I don't know where it come out from... sure nothing about Christ !!!)

Than I try to modify lambda_function.py with my pubblic playlist ID
- open https://www.youtube.com/playlist?list=PLWHIkUMZKqSwxPLIiX_ODsvabasbKCiNL
copy only text "PLWHIkUMZKqSwxPLIiX_ODsvabasbKCiNL"
- open AWS, click lambda, YoutubeSkills,
(error opening file - could not open file: /index.js - the file could not be found on the file system - ok)
- double click on lambda_function.py
Modify line 451
from
playlist_id = 'PLLFnyGeZhCiftnui2P1pBkenb352i0bqb'
to
playlist_id = 'PLWHIkUMZKqSwxPLIiX_ODsvabasbKCiNL'
Modify line 453
from
playlist_title = 'musique de christophe du nord'
to
playlist_title = 'cartongesso'
(the name of my playlist)
inside environment window: file/ save all
in the right top of the screen: save

Nothing is different from before...
if I ask "Alexa, chiedi a youtube": "Inizia la mia playlist", or "Ascolta la mia playlist", or "Riprodurre la mia playlist"
The answer is: "There is a problem with this skill"
If I ask "Alexa, chiedi a youtube": "Riproduci la mia playlist"
It play the same italian video I told you: https://www.youtube.com/watch?v=HlOD2k9q4JM

which is the problem ? What I wrong ?
Thank you a lot again...
​

**Comment by christ59** [comment] 2019-01-10 08:01
When you import the zip file, you have to choose "python" and not "json" or something else.

**Comment by ndg63276** [comment] 2019-01-10 09:33
@Carlo-Ita - christ59 is right, you need to open AWS, click lambda, YoutubeSkills, scroll down to function code, and change the Runtime to Python2.7, and then Save.

**Comment by ndg63276** [comment] 2019-01-10 10:51
Ok, I've rewritten this a bit, and merged the branch back into the master. Now you can just set an environment variable (MY_PLAYLIST_ID) with your playlist ID, which is tidier than editing the code.

I still want to implement a NextPlaylistIntent, will need some thinking over.

**Comment by christ59** [comment] 2019-01-10 11:21
Excellent!
I'll wait for the NextPlaylistIntent to recreate my Skill.
Do you think it's possible to search for a custom channel and then have our playlists (and the Nextplaylist function)?
Thank you.

**Comment by Carlo-Ita** [comment] 2019-01-10 14:55
Ok, I tried it, but still don't play my playlist but an other...
And there is the error "could not open file: /index.py"
in fact there is no file called "index" inside the zip
Maybe I have to change inside "gestor" from "index.handler" to "lambda_function.handler" (the .py file who contains the playlist ID) ?

Anyway I think that most of people in youtube have more than one playlist in theyr account (I've got 50...) and they continuously create new once...
And to add a playlist ID inside the file anytime you create a new one it's complycate...
So it would be nice to find the way to explane Alexa when to search the playlist name in all youtube, and when search it only inside my account...
So in the code you have only to change your account ID one time for all...
I don't know if this is what you are trying to do at the moment

**Comment by ndg63276** [comment] 2019-01-10 15:53
@Carlo-Ita - Yes the Handler (Gestor) should be "lambda_function.lambda_handler".

At the moment, I have no plans to search for playlists by account name, it would be slow and require some fuzzy string matching. I'll think about it.

**Comment by ndg63276** [comment] 2019-01-11 09:40
@christ59 - NextPlaylistIntent now available (in English, at least). Seems to work ok, but I haven't done much testing, so let me know how you get on.

I agree with you and Carlo, I should change it so you supply your ChannelId and then you could search your playlists. Needs a little work though.

**Comment by christ59** [comment] 2019-01-11 10:19
It's good news !
I look forward to the version with access to our channel!
Thank you for all the work done!

Something strange (and that may be related to all skills). Yesterday, I used my Skill Youtube, while listening to my playlist, I asked Alexa "Drop in, ...", the Drop In (to communicate between Echo) was well activated but the music continued to play !!! We had trouble understanding each other, LOL.

**Comment by Carlo-Ita** [comment] 2019-01-11 13:41
@ndg63276 wow It's really a fantastic news !!!

Also if i'm not able to make the skill works right... and it plays the Chhrist's playlist (which is very pleasant, but I would prefer mine...!! ) also if the text in the lambda function it's correct with my ID and playlist name...
So my doubt is that maybe it is not enough to just edit the text inside the web page as in a word file and save, but when you say "edit" you mean using another program ...
Anyway I do not want to stress you for something that maybe will change, so I'll wait for the new version you're working on

**Comment by christ59** [comment] 2019-01-11 14:04
@Carlo-Ita
In lambda_function.py, in your AWS.
Line 456 : (playlist_id = 'PLLFnyGeZhCiftnui2P1pBkenb352i0bqb') it's the ID of my playlist. Put here yours.
Then save.
Test your Skill again.
If it still does not work, maybe you need to replace "MY_PLAYLIST_ID" lines 457 and 458 with your playlist ID.

**Comment by Carlo-Ita** [comment] 2019-01-11 14:56
thanks Christs, but I think our files are different and consequently also the line numbers...
the file currently has these lines, but the music is still yours ...

Line 430 :     playlist_id = 'PLWHIkUMZKqSwxPLIiX_ODsvabasbKCiNL'
Line 431 :     logger.info('Playlist info: https://www.youtube.com/playlist?list='+playlist_id)
Line 432 :  #    playlist_title = search_response.get('items')[sr]['snippet']['title']
Line 433 :     playlist_title = 'cartongesso'

**Comment by christ59** [comment] 2019-01-11 15:10
> thanks Christs, but I think our files are different and consequently also the line numbers...
> the file currently has these lines, but the music is still yours ...

I do not understand that he can play my playlist when you put the ID of your playlist!
Did you search all the code if there is not a place where the ID of my playlist would be written?
Can you put your lambda_function.py file here (in a ZIP) so that I look where the problem is coming from?
Via a private message if you wish.

**Comment by christ59** [comment] 2019-01-11 15:31
The file no longer exists. Can you put your file in a zip here?

**Comment by Carlo-Ita** [comment] 2019-01-11 15:38
[lambda_function.zip](https://github.com/ndg63276/alexa-youtube/files/2750184/lambda_function.zip)

**Comment by Carlo-Ita** [comment] 2019-01-11 15:41
in the zip there are two files:
lambda_fuction.py
lambda_function.py~
Maybe the problem is this one ?

**Comment by christ59** [comment] 2019-01-11 16:04
Yes, It will not work: **lambda_function.py~**
**lambda_function.py**: In the one that works I have: **playlist_id = 'PLLFnyGeZhCiftnui2P1pBkenb352i0bqb'**, This is my playlist.
I can not find the ID of your playlist '**PLWHIkUMZKqSwxPLIiX_ODsvabasbKCiNL**'
The recording does not seem to work.

**Comment by christ59** [comment] 2019-01-11 16:10
The easiest way is to make the changes directly on the AWS platform, not with Word or other.

**Comment by ndg63276** [comment] 2019-01-11 16:44
Hey guys, ignore the lambda_function.py~ file, that is just a relic from my text editor.

Best thing to do is to use the latest version of lambda_function.zip (https://github.com/ndg63276/alexa-youtube/blob/master/lambda_function.zip), upload that to Lambda, then set an environment variable. Below where you have set DEVELOPER_KEY, set another one for MY_PLAYLIST_ID, and put in the string for your playlist, eg PLWHIkUMZKqSwxPLIiX_ODsvabasbKCiNL, as the value.

Or just wait a few days, I will rewrite it to search just your playlists if you ask it to.

**Comment by Carlo-Ita** [comment] 2019-01-11 17:07
Thanks Christ, It's exactly what I do, but I don't know how to create a zip from aws, so I sent you the one I upload

**Comment by Carlo-Ita** [comment] 2019-01-11 17:07
![immagine](https://user-images.githubusercontent.com/46457212/51048607-b6260480-15cb-11e9-8d4c-ded4843ab90e.png)

**Comment by Carlo-Ita** [comment] 2019-01-11 17:10
Anyway I will wait the new file from ndg63276. Thanks to all of you

**Comment by ndg63276** [comment] 2019-01-12 00:19
OK, I've made a new commit, re-upload the latest lambda_function.zip to Lambda, and re-upload the InteractionModel_en.json to the Developer Console (if you translate it, let me know and I will update). Save and Build.

Then in Lambda, add another Environment Variable, called MY_CHANNEL_ID. The value is that of your channel ID, which you can get by finding one of your videos, then clicking your name underneath it. If it takes you to https://www.youtube.com/channel/UCDVYQ4Zhbm3S2dlz7P1GBDg, then your channel ID is UCDVYQ4Zhbm3S2dlz7P1GBDg.

You can delete the variable MY_PLAYLIST_ID if you made one, it is no longer used.

Then you should be able to say "Alexa, ask YouTube to play my playlist {name of playlist}", and it will just search your playlists.

Limitations:
* Public playlists only
* The "Alexa, ask YouTube for the next playlist" function will revert to all playlists, not just yours (to be fixed)

Let me know if it works, very limited testing!

**Comment by Carlo-Ita** [comment] 2019-01-12 06:17
@ndg63276 
hire some little grammar corrections for the new lambda file
line 67:
'welcome1':"Benvenuto su YouTube. Dì, per esempio, riproduci video dei Beatles.",
line 69:
'help':"Per esempio dì, riproduci i video dei Fall out Boy",

line 80 is grammatically correct, but it's not very nice to listen it, so, if for you it's ok, it's sound better so:
'noresume':"Non ero in grado di riprendere il video.",
(I wasn't able to resume the video)

**Comment by Carlo-Ita** [comment] 2019-01-12 06:33
So where do I have to put my channal id ?
Maybe in line 456 ? (   channel_id = '' )
So the example result is:
line 456:     channel_id = 'UCDVYQ4Zhbm3S2dlz7P1GBDg'

Or maybe in line 458 ? (        channel_id = environ['MY_CHANNEL_ID'] )
So the example result is:
line 458 :        channel_id = environ['UCDVYQ4Zhbm3S2dlz7P1GBDg']

**Comment by ndg63276** [comment] 2019-01-12 12:42
Don't edit the lambda_function.py. Instead, add an "Environment Variable". In the same way you have added DEVELOPER_KEY, add another called MY_CHANNEL_ID, with your channel ID as the value.

I have updated the Italian phrases, thanks.

**Comment by Carlo-Ita** [comment] 2019-01-12 15:43
I don't know exactly what do you mean with "add an Environment Variable, and I don't think I've done a DEVELOPER_KEY... but maybe it's what I've done in the immage...
![senza titolo-1](https://user-images.githubusercontent.com/46457212/51075214-f3040100-1688-11e9-9b70-d70e10c42cc4.jpg)

**Comment by ndg63276** [comment] 2019-01-12 22:38
Yes that's exactly right.

The skill may not work without a DEVELOPER_KEY variable. There are some instructions here - https://www.slickremix.com/docs/get-api-key-for-youtube/

**Comment by Carlo-Ita** [comment] 2019-01-13 01:48
I created an environment variable called DEVELOPER_KEY and on the right I past the key I've got on google following your link, but I don't understand the step N° 9 in the link you posted... can you help me ?

**Comment by ndg63276** [comment] 2019-01-13 08:33
Go to https://developer.amazon.com/alexa/console/ask#, and click on your YouTube skill. On the left, below JSON editor, should be a button labelled Interfaces.

![image](https://user-images.githubusercontent.com/24956497/51083182-9ac31280-170d-11e9-9a42-9de94da04e0e.png)

Click that, then make sure the top slider "Audio Player" is to the right.

![image](https://user-images.githubusercontent.com/24956497/51083193-c6de9380-170d-11e9-8385-d2b28168f99f.png)

Then click Save Interfaces, and then Build Model.

**Comment by Carlo-Ita** [comment] 2019-01-13 10:55
Yes I did it at the beginning, I meen this step N°9 ... I think It's something inside youtube option that I don't find...
![senza titolo-2](https://user-images.githubusercontent.com/46457212/51084443-09ae6480-172a-11e9-9e9b-3cef3bc8444b.jpg)

**Comment by ndg63276** [comment] 2019-01-13 15:13
Oh sorry, I misunderstood.

You don't need to do step 9, you just need the API key from step 8. Then put it in Lambda as DEVELOPER_KEY, which I think you already did, and the skill should work.

**Comment by Carlo-Ita** [comment] 2019-01-17 18:59
well, I deleted all and I follow your step from the beginning and now it seems to work.
(At the begin I followed an external tutorial)
The only problem is that it let me listen the playlist I already have in my channal before I built the skill, but not new once... (they are all pubblic list and they have the same video inside...)
When I ask for the newest, it say "there is a problem by the answer of the skill"

**Comment by Carlo-Ita** [comment] 2019-01-17 19:01
here you have a complete italian interaction model text:

[ita.txt](https://github.com/ndg63276/alexa-youtube/files/2770193/ita.txt)

**Comment by ndg63276** [comment] 2019-01-24 11:32
Oh, that's a bit crap of Google to cache the search results. Unfortunately, the playlists API doens't let you search, it just lists them, so I'd have to do the searching myself, which is messy and I'd rather not do.

**Comment by ndg63276** [comment] 2019-01-24 11:38
If you change your q parameter to 'musica' instead of 'music', it works for me:

https://www.googleapis.com/youtube/v3/search?part=id%2Csnippet&channelId=UCuyfyQyluS4CebRHwgSo5Yw&q=musica&type=playlist&key={YOUR_API_KEY}

**Comment by Mferrari85** [comment] 2019-01-24 14:03
> If you change your q parameter to 'musica' instead of 'music', it works for me:
> 
> [https://www.googleapis.com/youtube/v3/search?part=id%2Csnippet&channelId=UCuyfyQyluS4CebRHwgSo5Yw&q=musica&type=playlist&key={YOUR_API_KEY}](https://www.googleapis.com/youtube/v3/search?part=id%2Csnippet&channelId=UCuyfyQyluS4CebRHwgSo5Yw&q=musica&type=playlist&key=%7BYOUR_API_KEY%7D)

Yes you are right, In my test I used "musica" but to get the screenshot I don't now why I forgot the last "a".
Anyway seems now the playlist is indexed and all works fine; to verify the caching hypothesis I created another public playlist called "TEST123" that is public and available on my YT channel
![yt playlists](https://user-images.githubusercontent.com/46992749/51682831-a6091e80-1fe8-11e9-8d7c-bbe4ca5ce9f8.PNG)

trying to access to this playlist result into an empy result json
[https://www.googleapis.com/youtube/v3/search?channelId=UCuyfyQyluS4CebRHwgSo5Yw&maxResults=10&q=TEST123&part=id%2Csnippet&alt=json&type=playlist&key=THE_KEY](https://www.googleapis.com/youtube/v3/search?channelId=UCuyfyQyluS4CebRHwgSo5Yw&maxResults=10&q=TEST123&part=id%2Csnippet&alt=json&type=playlist&key=THE_KEY)

I will try to access again tomorrow after 24 hours to verify the hypothesis.
Anyway thanks for your time

**Comment by Carlo-Ita** [comment] 2019-02-01 01:53
@Mferrari85 can you explain to me what you did step by step to solve the problem ? grazie !!

**Comment by christ59** [comment] 2019-02-07 11:15
Hi, I'm back. I decide to update my skill with the latest version of your code.
"my playlist" does not seem to work.
In the "def search" function, there is no call to "MyPlaylistIntent". Is this normal or a forgetting?

**Comment by ndg63276** [comment] 2019-02-07 11:25
Hi again. MyPlaylistIntent is referenced on lines 359-361, so it should still work:
```
    search_intents = ["SearchIntent", "PlayOneIntent", "PlaylistIntent", "MyPlaylistIntent", "ShuffleMyPlaylistIntent", "ChannelIntent", "ShuffleIntent", "ShufflePlaylistIntent", "ShuffleChannelIntent"]
    if intent_name in search_intents:
        return search(intent, session)
```

**Comment by christ59** [comment] 2019-02-07 11:49
Yes, but does not it miss that:
elif intent_name == **"MyPlaylistIntent"** or intent_name == "SearchMyPlaylistsIntent" or intent_name == "ShuffleMyPlaylistsIntent":

**Comment by christ59** [comment] 2019-02-07 11:53
In "InteractionModel_en.json" there are no Intents "MyPlaylist", "SearchMyPlaylistsIntent" nor "ShuffleMyPlaylistsIntent"

**Comment by ndg63276** [comment] 2019-02-07 12:00
Yeah I broke it on this commit https://github.com/ndg63276/alexa-youtube/commit/0bdf792b8e880a92992f53c6c569262679328a07#diff-1c9600c715669119bf71f4577630e8a4 - thanks for spotting. Have updated the lambda_function.py and zip.

These Intents are only in English and Italian, just because I haven't got anyone to translate them to other languages.

**Comment by christ59** [comment] 2019-02-07 12:51
Damn. I should have kept my version. Now I do not access my playlist anymore -_-
It is possible to have a full version with access to his playlist in French? What do you want me to translate?

**Comment by ndg63276** [comment] 2019-02-07 12:53
Just these:

- "Start my playlist {query}"
- "Listen to my playlist {query}"
- "Play my playlist {query}"
- "Shuffle my playlist {query}"

**Comment by christ59** [comment] 2019-02-07 13:01
Démarrer ma playlist {query}
Lire ma playlist {query}
Jouer ma playlist {query}
Lancer ma playlist {query}
Ma playlist aléatoire {query}

Il y a ça aussi : "The video" = "La video"

**Comment by christ59** [comment] 2019-02-07 13:33
When importing **lambda_function.zip**, is it better to use **Python 2.7**, **3.6** or **3.7**?
Thank you.

**Comment by ndg63276** [comment] 2019-02-07 14:03
Ok, there's a new version of InteractionModel_fr.json, try with that. If you haven't already, you'll need to add the Environment Variable MY_CHANNEL_ID as your YouTube channel ID.

Use python 2.7 for lambda.

**Comment by christ59** [comment] 2019-02-07 14:32
It does not work. It does not read my playlist. I do not understand where the problem comes from.

**Comment by christ59** [comment] 2019-02-07 14:52
I have a playlist called "jean michel jarre". When I ask him to play my playlist "jean michel jarre", she plays "jean michel jarre" but not that of my playlist!

**Comment by ndg63276** [comment] 2019-02-07 14:54
Do you have the address of the playlist?

**Comment by christ59** [comment] 2019-02-07 14:54
Yes, my channel : UCidqxBUO_zV7JMpuumTCAmw

**Comment by christ59** [comment] 2019-02-07 14:57
https://www.youtube.com/playlist?list=PLLFnyGeZhCifi2Z12lKSSlZ7ppHYPD5Y1

**Comment by christ59** [comment] 2019-02-07 15:02
When i test on my PC, i have this message:
**AudioPlayer is currently an unsupported namespace. Check the device log for more information.**
What does it mean ?

**Comment by christ59** [comment] 2019-02-07 15:15
I think I have found where the problem comes from. My Skill does not connect to the proper function of the AWS server. The endpoint is good, but in the log, it's not good. It's strange.

**Comment by christ59** [comment] 2019-02-07 15:24
My Skill continues to want to connect to an old function, while the endpoint redirects to the new function. How can I change that? It looks like a bug!

**Comment by ndg63276** [comment] 2019-02-07 15:51
Ok, a few things here.
- Your playlist is very new, they take a while to appear on Youtube search. If you go to https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.search.list?part=id%252C+snippet&channelId=UCidqxBUO_zV7JMpuumTCAmw&maxResults=10&q=jarre&type=playlist&_h=1&, and click Execute Without OAuth at the bottom, you get 0 results. Try an older playlist.
- "AudioPlayer is currently an unsupported namespace" is perfectly normal, it just means your browser won't play the audio, but Alexa will.
- Make sure you set your endpoint as the default endpoint, and then click Save Endpoints. That should change instantly.

**Comment by christ59** [comment] 2019-02-07 16:07
It is the end. I recreated a Skill, I recreated an AWS but nothing else works. Communication between the Skill and AWS does not work anymore, I do not know what's going on.

**Comment by ndg63276** [comment] 2019-02-07 16:13
Hah, such pessimism. Set your endpoint to my lambda skill, arn:aws:lambda:eu-west-1:175548706300:function:YouTube. It works fine.

**Comment by christ59** [comment] 2019-02-07 16:22
My Alexa developer console does not seem to work anymore. Even by changing the invocation name, she is still looking for the old invocation name.

**Comment by ndg63276** [comment] 2019-02-07 16:24
The invocation name is also in the InteractionModel_fr.json file, so if you re-upload that file, it will set it back to YouTube.

**Comment by christ59** [comment] 2019-02-07 16:29
I'm giving up. It works with your ARN. I will stay on it. I do not know what's going on with mine. 
I might try again tomorrow. Thanks for your help.

**Comment by doctorchuchu** [comment] 2019-02-07 20:54
Hmm, I seem to be having the same issue with playing my own playlist. I set up my own Lambda and everything works except my own playlist. I tried the Google APIs Explorer and it comes up with 0 results, so I assume that's the issue? Though I tried it with a more popular channel and Alexa still gives me error. I checked the Lambda log and it just says Invalid intent: ValueError.

**Comment by doctorchuchu** [comment] 2019-02-07 21:03
Actually I looked at the log more closely. It looks like it ended on line 403 on the last else to return an error. I see that the name of the intent on the Alexa Developer side is "SearchMyPlaylistsIntent," which isn't handled at all in the lambda function. How do I update it so I can use this intent?

**Comment by ndg63276** [comment] 2019-02-07 21:09
The latest lambda_function.py (or lambda_function.zip) handles SearchMyPlaylistsIntent:

```
    search_intents = ["SearchIntent", "PlayOneIntent", "PlaylistIntent", "SearchMyPlaylistsIntent", "ShuffleMyPlaylistsIntent", "ChannelIntent", "ShuffleIntent", "ShufflePlaylistIntent", "ShuffleChannelIntent"]
    if intent_name in search_intents:
        return search(intent, session)
```

Update and try again.

**Comment by doctorchuchu** [comment] 2019-02-07 21:12
Oh yeah it works, except for some reason the Google API can't find my playlist still. It works with other channels though. Any way to update your channel/playlist so that it shows up?

**Comment by ndg63276** [comment] 2019-02-07 21:19
It's very unclear how it works. I would say make sure you have a few videos on the playlist, as I made a 1 video playlist about a month ago, and it has never shown up in search results.

**Comment by doctorchuchu** [comment] 2019-02-07 21:32
Hmm, my playlist and my newly created test playlists show up when I use the function youtube.search.list. However it doesn't look like there's a field for queries.

**Comment by ndg63276** [comment] 2019-02-07 21:48
Yep, that was the conclusion I came to earlier in this thread.

**Comment by ndg63276** [comment] 2019-02-07 22:26
Yeah, change (in my_playlists_search)
```
    search_response = youtube.search().list(
        q=query,
        part='id,snippet',
        maxResults=10,
        type='playlist',
        channelId=channel_id
        ).execute()
```
to
```
    search_response = youtube.playlists().list(channelId=channel_id,part='id,snippet').execute()
```

**Comment by doctorchuchu** [comment] 2019-02-07 22:33
Thanks for the response. The youtube.playlists.list returns only id for the playlist ID. So I think playlist_id is not assigned correctly, which then throws an error a few lines down.

**Comment by ndg63276** [comment] 2019-02-07 23:57
Oh I see. Change that loop to
```
    for playlist in range(sr, len(search_response.get('items'))):
        if 'id' in search_response.get('items')[playlist]:
            playlist_id = search_response.get('items')[playlist]['id']
            break
```

**Comment by doctorchuchu** [comment] 2019-02-08 04:15
Dude thanks so much. It works 😄

**Comment by doctorchuchu** [comment] 2019-02-08 17:13
I'm not sure how Github works, but there is a small error where the ShuffleMyPlaylistsIntent is misspelled in the Lambda (ShuffleMyPlaylistIntent).

**Comment by ndg63276** [comment] 2019-02-08 17:19
I think I fixed that in https://github.com/ndg63276/alexa-youtube/commit/5950bd5b390871efdf6fe07da3b645edb3f1363e.

**Comment by doctorchuchu** [comment] 2019-02-08 21:08
Could you have ShuffleMyPlaylistsIntent continually loop? And, if possible, reshuffle the order of videos each loop?

**Comment by ndg63276** [comment] 2019-02-09 14:09
Ok done. I am too good to you.

I'm going to close this issue now, because it's gotten too big. Anyone that still has problems, please create a new issue.

**Closed by ndg63276** 2019-02-09 14:09 UTC
