### ISSUE TITLE
Forward and backward in Amazon Echo dot 3rd generation

### ISSUE THREAD

**Issue by Ambro86** [ndg63276/alexa-youtube#132] opened 2019-11-24 08:22 UTC
Hi, first of all thanks for this excellent skill. It greatly extends the possibilities of Alexa. I would like to report a problem to you. I have a third generation Amazon Echo. The videos reproduce correctly, but if I say, skyp forward 30 seconds the video freezes and no longer plays. Is there a way to solve this problem?
Thanks.

**Comment by ndg63276** [comment] 2019-11-24 09:06
Does Alexa say anything when you ask her to skip? She should say OK.

**Comment by Ambro86** [comment] 2019-11-24 09:21
Hello, yes, Alexa says ok, but freezes and don't play anything.
Another thing. I am using the skill in italian, and the playlist thing
doesn't work. If I say "Alexa chiedi a youtube di riprodurre la
playlist xxx", she plays the video if she finds it. If I say "alexa
riproduci playlist successiva", that is "alexa plays the next
playlist", she understand to play next video, not next playlist.
Thanks a lot.

2019-11-24 10:06 GMT+01:00, ndg63276 <notifications@github.com>:

**Comment by ndg63276** [comment] 2019-11-24 10:21
You have to say "Alexa chiedi a youtube di riproduci playlist successiva".

**Comment by ndg63276** [comment] 2019-11-24 10:26
I am unable to reproduce your first problem, saying "Alexa, chiedi a youtube andare avanti di 30 secondi". Does it happen with all videos, or only a few?

**Comment by Ambro86** [comment] 2019-11-24 10:55
Thanks for the reply. Yes, it happens on all the videos I've tried. I tried to say: "Alexa, riproduci video dei beatles. The song Hey Jude correctly reproduced.  Now: alexa, vai avanti di 20 secondi. She told me ok, but the video didn't play anymore. At this point I tried to say, alexa, riproduci. She told me ok but did nothing. Saying Alexa, pausa (that is pause), he said hello from youtube. Then I said: alexa apri youtube (open youtube), and then I said riproduci (reproduce), to reproduce what had been left hanging. He told me that there was an error with the skill.
Can it depend on the amount of memory set? I set ram 512 mb, and on timeout 10 seconds.

**Comment by ndg63276** [comment] 2019-11-24 11:15
512mb and 10 seconds should be fine.

Can you change your endpoint to arn:aws:lambda:eu-west-1:175548706300:function:ambro86 ? Then do the same actions again and I can look at the logs.

**Comment by Ambro86** [comment] 2019-11-24 11:53
Hi, of course. I changed the endpoint. I played a Beatles video. Then I skypped ahead 20 seconds. I did several tests in short. I think you will see the error.

**Comment by ndg63276** [comment] 2019-11-24 13:19
Ok, I found one error, where asking for the next playlist fails because youtube returns no search results for playlists (https://www.youtube.com/results?search_query=flora+piccola+robinson+la+lettera&sp=EgIQAw%253D%253D)

I've updated that ARN, can you test again? I haven't found anything to do with the skipping problem.

**Comment by ndg63276** [comment] 2019-11-24 13:26
Oh, and now I find this error: MEDIA_ERROR_SERVICE_UNAVAILABLE

Amazon is very vague as to what this means though, possibly a slow connection? https://forums.developer.amazon.com/questions/84734/request-timed-out-media-error-service-unavailable.html

**Comment by ndg63276** [comment] 2019-11-24 13:29
By the way, youtube search for Flora Piccola playlists seems very bad. If you have favourite playlists, you can set them in the Youtube Favorites list in the Alexa app. Just add an item to the list that looks like this:

Flora Piccola | https://www.youtube.com/playlist?list=PLBAZdkX9T9KAtb3C2YK5rconCtA1YGzBC

Then you can just say "Alexa, ask Youtube to play Flora Piccola" and she should find that instead of searching youtube.

**Comment by Ambro86** [comment] 2019-11-24 13:38
Thanks for the correction. In fact now the error of the playlist does not happen anymore. It's a pity that nothing can be done for skipping forward and backward. Could it be that I have to change values?
In any case there is another problem that I found. Sometimes Alexa reads the wrong video titles. In the log you will find that I have played a video. Alexa says: I play video più bella cosa of Eros Ramazzotti. Instead it is not that song but it is Un'altra te.
Then saying Alexa, next, he told me: I play ramazzotti per le strade una canzone, with Luis Fonsy.
But here too it's wrong, it's Instead it's Cose della vita with Tina Turner.
It is possible to correct that?

**Comment by ndg63276** [comment] 2019-11-24 13:42
Unfortunately not. She intends to play a song and announces it. Then she tries to actually play it, finds she can't play it (I dont know why), so she plays the next one in the search results. But there is no way to know beforehand which videos will work.

**Comment by Ambro86** [comment] 2019-11-24 13:54
Ok thanks. I will try more if I find more problems.

**Comment by Ambro86** [comment] 2019-11-24 14:26
I've tried to add a playlist in the youtube favourite's list, but it didn't work. I don't know if I'm doing something wrong.

**Comment by Ambro86** [comment] 2019-11-24 14:33
I've tried to play also playlist that are already presents but doesn't work. For example that song I like.

**Comment by ndg63276** [comment] 2019-11-24 14:34
The address in your list doesn't work, there is a bracket that should be a question mark, and some characters missing.
You have:
https://www.youtube.com/playlist(list=PLBAZdkX9T9KAtb3C2YKnCtA1YGzBC
It should be:
https://www.youtube.com/playlist?list=PLBAZdkX9T9KAtb3C2YK5rconCtA1YGzBC

If you find the playlist in the youtube app, there is a "share" button, then you can press "Copy link", then you can copy it into the Alexa app lists.

**Comment by ndg63276** [comment] 2019-11-24 14:38
> I've tried to play also playlist that are already presents but doesn't work. For example that song I like.

It appears "That song I like" is no longer on your favorites list... is it marked as completed? They are ignored.

**Comment by Ambro86** [comment] 2019-11-24 14:42
I did it! Thanks!

**Comment by ndg63276** [comment] 2019-11-24 14:45
Great!

Can you put your original endpoint back? So I can delete the one I gave you.

**Comment by Ambro86** [comment] 2019-11-24 14:50
Of course, thanks again! I'd like to ask you a question. When should I upload the updated lambda_function.zip file, as I do without having to delete the function I had created? Is there a way to delete the zip file I uploaded to aws.amazon.com?

**Comment by ndg63276** [comment] 2019-11-24 15:04
If you upload the updated lambda_function.zip file, it will update the files that have changed. You don't need to delete the zip file.

**Comment by Ambro86** [comment] 2019-11-24 15:36
Thanks a lot.
Cheers,
Ambro

**Closed** 2019-11-24 21:17 UTC
Labels: bug
